# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6eb1177198c1ff00819639fe9aae7f4af318c5db1e0146d6445a015053b37ffda97ecd24b7474d895f01854217ee47e2ab68c0812603b24d44b4e1c03fab36f7

test:
  secret_key_base: dc4b491c4dc821430b1144799b5b2566c906284a4721bbfa21221a7eb0a586455e11903971fef08014a47e2b82fc7f48ee1a32dddcb55a4ba674625579ffd87b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
